config/routes.rb
Rails.application.routes.draw do
  root 'index#index'

  resources :players
  resources :teams
  resources :sponsors
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/player.rb
class Player < ApplicationRecord
  belongs_to :team
  
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :born, presence: true
end

app/models/sponsor.rb
class Sponsor < ApplicationRecord
  has_many :team_sponsors
  has_many :teams, through: :team_sponsors
  validates :name, presence: true
end

app/models/team.rb
class Team < ApplicationRecord
  has_many :team_sponsors
  has_many :sponsors, through: :team_sponsors
  has_many :players

  validates :name, presence: true
end

app/models/team_sponsor.rb
class TeamSponsor < ApplicationRecord
  belongs_to :sponsor
  belongs_to :team
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def index
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def index
    @players = Player.all
  end

  def create
    @player = Player.create(player_params)
    if @player.save
      redirect_to players_path
    else
      render :new
    end
  end

  def edit
    @player = Player.find(params[:id])
  end

  def update
    @player = Player.find(params[:id])
    if @player.update(player_params)
      redirect_to players_path
    else
      render :edit
    end
  end

  def destroy
    @player = Player.find(params[:id])
    if @player.destroy
      redirect_to players_path
    else
      render :index
    end
  end

  def new
    @player = Player.new
  end

  private

  def player_params
    params.require(:player).permit(:first_name, :last_name, :born, :team_id)
  end
end

app/controllers/sponsors_controller.rb
class SponsorsController < ApplicationController
  def index
    @sponsors = Sponsor.all
  end

  def create
    @sponsor = Sponsor.create(sponsor_params)
    if @sponsor.save
      redirect_to sponsors_path
    else
      render :new
    end
  end

  def edit
    @sponsor = Sponsor.find(params[:id])
  end

  def update
    @sponsor = Sponsor.find(params[:id])
    if @sponsor.update(sponsor_params)
      redirect_to sponsors_path
    else
      render :edit
    end
  end

  def destroy
    @sponsor = Sponsor.find(params[:id])
    if @sponsor.destroy
      redirect_to sponsors_path
    else
      render :index
    end
  end

  def new
    @sponsor = Sponsor.new
  end

  private

  def sponsor_params
    params.require(:sponsor).permit(:name)
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  def index
    @teams = Team.all
  end

  def create
    @team = Team.create(team_params)
    if @team.save
      redirect_to teams_path
    else
      render :new
    end
  end

  def edit
    @team = Team.find(params[:id])
  end

  def update
    @team = Team.find(params[:id])
    if @team.update(team_params)
      redirect_to teams_path
    else
      render :edit
    end
  end

  def destroy
    @team = Team.find(params[:id])
    if @team.destroy
      redirect_to teams_path
    else
      render :index
    end
  end

  def new
    @team = Team.new
  end

  private

  def team_params
    params.require(:team).permit(:name, sponsor_ids: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/sponsors_helper.rb
module SponsorsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/index/index.html.erb
<h1>Hi</h1>

<%= link_to 'Players', players_path %>
<%= link_to 'Teams', teams_path %>
<%= link_to 'Sponsors', sponsors_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FootballApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/players/_fields.html.erb
<% @players.each do |player| %>
  <tr>
    <td><%= player.first_name %></td>
    <td><%= player.last_name %></td>
    <td><%= player.born %></td>
    <td><%= player.team.name %></td>
    <td><%= link_to 'delete', player_path(player), method: :delete %></td>
    <td><%= link_to 'edit', edit_player_path(player) %></td>

  </tr>
<% end %>

app/views/players/_nav.html.erb
<tr>
  <th>first_name</th>
  <th>last_name</th>
  <th>born</th>
  <th>team</th>
  <th>options</th>
</tr>

app/views/players/edit.html.erb
<h1>Edit user</h1>
<%= simple_form_for @player do |f| %>
  <%= f.input :first_name %>
  <%= f.input :last_name %>
  <%= f.input :born, as: :date %>
  <%= f.input :team_id, collection: Team.all %>
  <%= f.button :submit %>
<% end %>

app/views/players/index.html.erb
<table class="table">
  <thead>
    <%= render 'nav' %>
  </thead>
  <tbody>
    <%= render 'fields' %>
  </tbody>
</table>

<%= link_to 'Create new player', new_player_path %>
<%= link_to 'Back', root_path %>

app/views/players/new.html.erb
<%= simple_form_for @player do |f| %>
  <%= f.input :first_name %>
  <%= f.input :last_name %>
  <%= f.input :born, as: :date %>
  <%= f.input :team_id, collection: Team.all %>
  <%= f.button :submit %>
<% end %>

app/views/sponsors/_fields.html.erb
<% @sponsors.each do |sponsor| %>
  <tr>
    <td><%= sponsor.name %></td>
    <td><%= link_to 'edit', edit_sponsor_path(sponsor) %></td>
    <td><%= link_to 'delete', sponsor_path(sponsor), method: :delete %></td>
  </tr>
<% end %>

app/views/sponsors/_nav.html.erb
<tr>
  <th>name</th>
  <th>options</th>
</tr>

app/views/sponsors/edit.html.erb
<%= simple_form_for @sponsor do |f| %>
  <%= f.input :name %>
  <%= f.button :submit %>
<% end %>

app/views/sponsors/index.html.erb
<table class="table">
  <thead>
    <%= render 'nav' %>
  </thead>
  <tbody>
    <%= render 'fields' %>
  </tbody>
</table>

<%= link_to 'Create new sponsor', new_sponsor_path %>
<%= link_to 'Back', root_path %>

app/views/sponsors/new.html.erb
<%= simple_form_for @sponsor do |f| %>
  <%= f.input :name %>
  <%= f.button :submit %>
<% end %>